$(document).ready(function(){
    $("#hideLogin").click(function(){
        $(".loginPannel").hide();
        $(".registerContainer").show();
    });
    $("#hideReg").click(function(){
        $(".loginPannel").show();
        $(".registerContainer").hide();
    });
});